language: clojure
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
deploy:
  skip_cleanup: true
  provider: script
  script: lein deploy
  on:
    tags: true
notifications:
  slack:
    secure: l1YPtmVN4ayN+i7nNUGkm96pwtS2MospyuU2k00LNbSEYM+yuFgXAN4WaxhHJ61UZCJUDsKULw1rEs1SEp2sdpvF8/gi/yqzgMHA3mVqe7rLZhPtahBk55HC4ShWLU4Rqw0nmBXpX1GK4946X/17Tylgsc61rBxPWZY/NYCp77c/nyvjbAoYd34Uel4x3+ShCsqAo9Sjxpq/nT6W06C2yEyieYAEnzlRN6gUMwSo2LscneTjcERPxjMkP9R7PEHBnRgxYq0b9b92omoEsUo4pa4lv79eTPvJCLjjdq4pdCmiqIT+1ZThz4gBDTeBmEDTwxuc/sRdB4U230N8IEpWGZFbYL/CgmnyCW+VTsyZrsq96ojZycRzxZJRztWNYoIUcz2s8HHmM8yaczTqyDg6BYUWm4Oq1rpe3zulCckd8fHcrcWbz1wVyLG8uJKSi8Kj5Fc0N5vdyIp5hWVvP5B6pv+2VSyZhFkEVHVGsMdmZ9x0/h2x4b0eqHUbsOimmCcFC+YoBAKjl4AGjzaeYOnpL8sli6c5ZkEdb6m/ahXZRcve0y2Z7LrmLqvNh9v1IVrFRS252q6+PSIMQ26ruazv87g81VgKCrmkHMzyh3Qi8FYR6j6ht5RJN+CKJV8GqwXqAdUJR7QUnNNdhxlRSO95zGL8CnqlbPrGTFGCSUIdKK0=
env:
  global:
  - secure: Jx9usW616sEZGOSH6XwG2XokOtD8t8Izh5vQH7ca1ybyxS+o2qGY96r08aatn8sEXkiNLQenwcYIZ7kg/f5n4adu5STA+fgwGEsk8PyaKweqoE3rSBa3F1DQqzWKEdpwU5vgtPmswvugMZIYWGnhQkob3nHFN/NL6GRuBKS1Z+wxpu5/lzSPnEavJ6O4dWq9Gdn1zudLLVLM1G0bFy4U1z7nFOF2Ahi5JPfRFLfYg90KAjNOFFT+e3W0XGAMRvL+iqKErg8Pvarbz4qVo2nnSz9fxq83lO3g5Gy90yUNIOS01BpdJUGNrqT4FTxc/R+7cjDLb6c89kPljAG9sh47g2A77FGid0DPgGbkD/3mCJFPjrATGLUKeSRN+K7FF01ZylJKcw98XcAxWLRMqvY49StqWrd5pJ+pyIRs9yTb9DpFxYNCpILd881G9hNiJPLruVP6NOuqxdyWRlS00FlO86k94div1FPAIFRgCK9fkMjGSfVcCbY9HoIbh/px/ehJhO37lgtQp2OFl6JwpIJSye+dlhoQqSPPHxsn+Kieg/MmkqqqXyj7MrTKc//Sx5sMW6+Fyr3EYUa4HwBWBNo+5vYcGBikyqSYSkDyjKDXlBG8QOox1aDTOKeYfaoJfLReI8g7b1VtBYKMM7gX2aa2XH4o/vP3LEyJzMD1hO0mbvg=
  - secure: hamC8Na/urMXaJuZhslrPqlLN2OYCW/g8km7V1AWg1g0CzM6PTyrDvO0CD9oDHAxabq8mN5BAtTPn6rBkQRJSvOBPZmGXUUaC/EII0jNqG9DmVyqChi+CnNR2gShaNuWGrmKNWw/WnafSBhwz6GJznj/98btxEltJWyiu9jaKUaIc/kFaN44o0i0GUxZHdgulkSkSVeiyiqxbaHCmjBXdUSKexBw7TKfdrYhNgtWtwjZMMytS4xPTolnXIL1deMyilqfp2KKeRhTodD0zrW71pyt+mGld+9hJIdC9/xfDJG7HAQcOm8eTiEBdQmBn4w5gUL5f4X5AqBiX8PPCqARWrtKiG2KHT/EysLnPEkzDd6cWOs+aN3AT37fHwEFzksegTzU+KbYB7nvMFR1Fnvt7fy8z4+rCF+PM3qVFWCQAGeJCTgw9Oyae5w3bL30GEdbBtLVnVLQJxmqspMJBXLQzE25EHDLrZQhXZEaWizffAjcK9sd55DzyWViPmjWJTQHs37Xco7+1hextv6hIt5gOKUh5tkXSNlQHFg1VofKR3XZcbXZZj4hFmB2r8v9jKj0wU1SUVZNIMgn9falrFwrm6Csp1GnBE9YD6NAfYWugcybibRsCjyUVC9FJdA0MwQSGHMWaiCjMoBzzW9CtIKMp5qqnBnMrYcoM5C6bwykIno=
